### ISSUE TITLE
Handling of query parameter encoding is incorrect 

### ISSUE THREAD

**Issue by Plausible0Bug** [ArchGPT/insomnium#121] opened 2023-12-17 18:51 UTC
### Expected Behavior

Setting a query parameter `search` to `%key%` should match the result of encodeURIComponent

### Actual Behavior

The result doesn't match encodeURIComponent

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/ArchGPT/insomnium/issues) for this problem.

### Insomnium Version

0.2.3-a

### What operating system are you using?

macOS

### Operating System Version

Sonoma

### Installation method

Release download

**Comment by archywillhe** [comment] 2023-12-17 22:03
Hi. I'm not able to reproduce this. `encodeURIComponent` works just fine. 

I'm closing this for now.

Please do feel free to give more elaboration

**Closed by archywillhe** 2023-12-17 22:03 UTC
